### ISSUE TITLE
Sol Expert

### ISSUE THREAD

**Issue by galou** [FreeCAD/FreeCAD-library#144]
Are we sure we want to have the "Sol Expert" folder in this repository? It doesn't appear to me to be close to any standard.

If we really want it, all spaces should be removed from the names and all files should be in English.

**Comment by Almisuifre** [comment]
I designed this library in relation to specific components for vehicles in 1:87 scale. One can get these components on the website Sol Expert Group ...

Several solutions possible.
1 / If this is concidered as unnecessary, remove it but remain in my github github perso ... My nefera more copy of the official github ...
2 / It is misplaced, then move, it poses any worries me.
3 / That remains as it allows and to benefit many

**Comment by galou** [comment]
Is 1:87 a standard modeling scale? In this case, we should only rename the directory to something more neutral like "Modeling/1_87" and let "Sol Expert" as subdirectory.

**Comment by wood-galaxy** [comment]
The models in the library does not have to be standard. However I agree that it might be to create a category named like "Reduced Models" ?

**Comment by normandc** [comment]
I believe the English expression is "scale model". https://en.wikipedia.org/wiki/Scale_model

So the directory tree could be FreeCAD-library/Scale Models/Sol Expert/1_87.

**Comment by Almisuifre** [comment]
It would be perfect if it could return to this logic.

**Comment by wood-galaxy** [comment]
A directory have been create. However about file name, I don't think english was so important, I prefer having more object than forcing people to translatefile name. One could always change the name and provide a pull request.
