### ISSUE TITLE
Cloud it be a bicycle store ?

### ISSUE THREAD

**Issue by FrViPofm** [FreeCAD/FreeCAD-library#208]
I have started one :  https://github.com/FrViPofm/Bike3D

But it would rather be among the other stores...

**Comment by normandc** [comment]
Please explain the purpose of this issue. The issue title and description make no sense to me.

**Comment by PrzemoF** [comment]
It seems strange, but .... I read it as : please move FreeCAD repo to gitlab. I'd close it if I could.

P.S.  I just learned github was acquired by MS. - get ready for embrace-extend-extinguish?

**Comment by dlastov** [comment]
If you want to contribute with bicycle models to the FreeCAD-library, so the instructions are here:
https://github.com/FreeCAD/FreeCAD-library#sharing-your-models-from-the-macro

**Comment by normandc** [comment]
Closing this issue. As @dlastov mentioned, a pull request is probably better suited - assuming @FrViPofm is still willing to have their work hosted on Github.
