### ISSUE TITLE
FreeCAD 0.17 with Win 10 - FreeCAD-library - PartsLibraryFC.Macro connection crashes app & gives Errors.

### ISSUE THREAD

**Issue by V8Skater** [FreeCAD/FreeCAD-library#233]
System:
Windows 10 upgrades from 7
64 bit O/S

I'm new to this, more like a beginner-beginner. Upon downloading FreeCAD to my Pc, I wanted to download the library parts too. Yes' I wanted everything in 1 go, but when I used the installer from the addon Manager, it took forever to download. Eventually, I clicked the install/update button and a message said it's already installed on my Pc. When I restarted FreeCAD, the main window never loaded or showed at all so I had to uninstall everything and start again.

I figured this was from a bug or something, and I had to uninstall all files, re-install FreeCAD and start over again. This has happened many, many times, I lost count after 10. Eventually, finding the issue had to do with the parts_library in the Addon Manager. I even tried downloading via GitHub.com and there was no difference.

I've tried following the awkward instructions and they're quite difficult to understand for a non computer person, but these were the messages I was receiving on Freecad Python once I figured how to view these messages:

python-git not found. Git-related functions will be disabled
Traceback (most recent call last):
  File "C:/Program Files/FreeCAD 0.17/macro/FreeCAD-library/PartsLibrary.FCMacro", line 468, in <module>
    m.addDockWidget(QtCore.Qt.RightDockWidgetArea,ExpDockWidget(LIBRARYPATH))
  File "C:/Program Files/FreeCAD 0.17/macro/FreeCAD-library/PartsLibrary.FCMacro", line 234, in __init__
    self.retranslateUi()
  File "C:/Program Files/FreeCAD 0.17/macro/FreeCAD-library/PartsLibrary.FCMacro", line 239, in retranslateUi
    self.setWindowTitle(translate("PartsLibrary", "Parts Library"))
  File "C:/Program Files/FreeCAD 0.17/macro/FreeCAD-library/PartsLibrary.FCMacro", line 96, in translate
    if sys.version_info.major >= 3:
<type 'exceptions.NameError'>: global name 'sys' is not defined

Am I missing something or does this program only work for linux instead of Windows, or are there errors within the program that needs fixing to work, if it is capable of working? Or am I only able to upload them directly to FreeCAD without a working panel?

Cheers.......

**Comment by luzpaz** [comment]
I recently saw a post about this in the FC forum. Can't find it ATM. Please open a forum thread to discuss this instead of an issue on this repo. Forum is the best place to get help.

**Comment by luzpaz** [comment]
@kprasadvnsi does this need to be added to the original macro to be more 'future friendly' ?

**Comment by kprasadvnsi** [comment]
i don't know. may be the repo admin can answer it better. i had the same problem on my linux machine and doing that fix the problem.

**Comment by luzpaz** [comment]
@V8Skater please test and close issue if fix works.

**Comment by V8Skater** [comment]
My parameters have already been set as kprasadvnsi described in the module, the sys already exists there. I have not changed any of them. 

I've tried to install the parts_library through the installer, however, this takes longer than I thought, and I've tried downloading the zip file through github and opening the files there. However, I'm unsure how to link these files directly to FreeCAD as the instructions are not very clear on how to do this. I have tried to create new macro and Macro folders in the bin folder, along with creating a new libs folder, though FreeCAD does not recognise these changes.

I've also tried following yorikvanhavre's advice by adding the missing import sys in the macro, However, this changes nothing. I'm aware part_library is quite a large file in total and I've waited for copious amounts of hours installing the files through the installer and github, but the instructions on github  aren't very clear. I'm not highly educated in the computer field but I can follow instructions if they're set correctly.

**Comment by normandc** [comment]
@V8Skater this issue is now more than 2 years old, and FreeCAD 0.17 is no longer current. V0.19 is due for release very soon, once the packagers address some issues. Please try again with the new release when it's available and report back. Thanks.
