### ISSUE TITLE
Can not run freecad on Debian Error libboost_filesystem.so.1.55.0 not found

### ISSUE THREAD

**Issue by dykon** [FreeCAD/FreeCAD-library#234]
Hi I try to run Freecad on Debian and I get this:
`freecad: error while loading shared libraries: libboost_filesystem.so.1.55.0: cannot open shared object file: No such file or directory
`
I have installed libboost and I got libboost-filesystem1.62.0 haw can i fix this issue to run freecad again.
Reinstall freecad had no effect.

Thanks for help

**Comment by normandc** [comment]
dykon, this is the FreeCAD_library repository, a repository of parts modelled in FreeCAD. This is *not* the place to ask for help on installing or running FreeCAD. Please register to the FreeCAD forum for that.
