### ISSUE TITLE
FreeCAD exception thrown (No write permission for file: /var/www/www-data/model.stl)

### ISSUE THREAD

**Issue by hadrizi** [FreeCAD/FreeCAD-library#238]
I'm making an online stp to stl converter and so i upload stp files and change them to stl, but when i try to save it i'm caught with an error that file got no write permissions however the folder i'm trying to download stl file is fully public

**Comment by luzpaz** [comment]
please open a https://forum.freecadweb.org thread to discuss this. Thx.

**Comment by hadrizi** [comment]
k

**Comment by luzpaz** [comment]
@hadrizi did you open a forum thread ?
