### ISSUE TITLE
[Parts] SVG Logo for this Addon is needed

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-library#243]
https://github.com/FreeCAD/FreeCAD-addons/issues/37

**Comment by luzpaz** [comment]
bump

**Comment by Mambix** [comment]
super busy, will do it this weekend :+1:

**Comment by Mambix** [comment]
https://github.com/FreeCAD/FreeCAD-addons/pull/147

renamed it to workbench to use proper FreeCAD naming and used latest code that contains SVG icon

**Comment by luzpaz** [comment]
Can you rebase and squash the PR ?
Also can you add the SVG logo to Master and update the relevant .qrc file ? https://github.com/FreeCAD/FreeCAD-addons/pull/147#issuecomment-522322801

**Comment by normandc** [comment]
Closing issue as per https://github.com/FreeCAD/FreeCAD-addons/pull/147#issuecomment-639423295
