### ISSUE TITLE
M4 Hex Nut has 8 sides

### ISSUE THREAD

**Issue by aalku** [FreeCAD/FreeCAD-library#254]
M4 Hex Nut has 8 sides

![image](https://user-images.githubusercontent.com/12587056/67638583-660ff880-f8e6-11e9-9556-a032e7a1e5a3.png)

**Comment by MountyRox** [comment]
I have detected a wrong dimension in my model "Electrical Parts/Enclosures/RND_455_00135.fcstd" which needs to be fixed. I can also fix the M4 Hex Nut within one pull request.

**Comment by hyarion** [comment]
@MountyRox As you mention in #285 that you fixed the issue, shouldn't this issue be closed?

**Comment by MountyRox** [comment]
@hyarion i agree, this issue can be closed. The bug fix of M4 Hex Nut was merged some month ago. Since @aalku opened this issue, he should close it.
