### ISSUE TITLE
parts library doesnt work for me under windows

### ISSUE THREAD

**Issue by urishab** [FreeCAD/FreeCAD-library#407]
Downloaded the 0.21.2 version of FreeCAD
from the **add-on menu** I install the parts library.
It gets installed fine (after a while) but there are no instructions on how to use it.
Running the PartsLibrary.FCMacro it asks me for the parts library location.
I point it to the right folder:
C:\Users\%username%\AppData\Roaming\FreeCAD\Mod\parts_library

But it doesn't show anything in the preview pane and I cannot navigate to the folder of the partslibrary beyond the **C:\Users\%username%\** part

I guess because the **"AppData"** folder is hidden?

THis is on Windows11

**Comment by shaise** [comment]
try C:\Users%username%\AppData\Roaming\FreeCAD\Mod\FreeCAD_library

**Comment by urishab** [comment]
I think I solved this by restarting FreeCAD
I also submitted a PR to add some instructions on using this addon as it was very unclear to me

**Comment by shaise** [comment]
Yes, they have installation instructions but not usage.
Also I do not think the plugin should hold the entire library locally.

**Comment by urishab** [comment]
They also write in the instructions that the BIM addon has a module for using the parts library in online-mode. I've tried it but it seems to be broken.

**Comment by shaise** [comment]
I'm working on the BIM add-on. I will try to revive the online-mode. If it works, perhaps I will create a separate macro for it, as it is useless to hold 5GB of parts locally.

**Comment by shaise** [comment]
I have fixed the broken bim on line library browser. I placed a pr for it.
Meanwhile if you want to test: https://github.com/shaise/BIM_Workbench
